version: "3.7"

services:
  ecr-ecs-deploy-local:
    build:
      context: .
      cache_from:
        - node:10.18
    ports:
      - 4000:4000
    tty: true
    networks:
      - appnet
  ecr-ecs-deploy-aws:
    image: 947663353871.dkr.ecr.us-east-2.amazonaws.com/ecr-ecs-deploy-repo
    environment:
      - POSTGRES_DB=testDb
      - POSTGRES_USER=testName
      - POSTGRES_PASSWORD=testPass
    ports:
      - 4200:4000
    networks:
      - appnet
networks:
  appnet:
    driver: "bridge"