version: "3.7"

services:
  ecr-ecs-deploy:
    build:
      context: .
      cache_from:
        - node:10.18
    ports:
      - 4000:4000
    tty: true
    networks:
      - appnet
networks:
  appnet:
    driver: "bridge"