# =========================================================================
# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy a new task definition to Amazon ECS (if any),
# on every push to the master branch.
# =========================================================================

on:
  push:
    branches:
      - master

name: Deploy to Amazon ECS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    # ==============================
    # CHECKOUT
    # ==============================
    - name: Checkout
      uses: actions/checkout@v1

    # ==============================
    # AWS CREDENTIALS CONFIGURATION
    # ==============================
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    # ==============================
    # LOGIN TO AWS ECR
    # ==============================
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # ==============================
    # RUN TEST
    # ==============================
    - name: npm install, build, and test
      run: |
        npm ci
        npm run test:ci
        npm run e2e
        npm run build:ssr
      env:
        CI: true
        DEBUG: '*'

    # ==============================
    # DEPLOY IMAGE TO AWS ECR
    # ==============================
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ecr-ecs-deploy-repo
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
